name: 5XSL0
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scipy
  - jupyterlab
  - tqdm
  - scikit-learn
  - ipykernel
  - pip
  - pip:
    - tensorflow